services:
  auth_service:
    url: "http://localhost:9001"
    routes:
      - path: "/api/login"
        target: "/login"
      - path: "/api/register"
        target: "/register"
      - path: "/api/account/me"
        target: "/me"
  review_service:
    url: "http://localhost:9002"
    routes:
      - path: "/review/hi"
        target: "/test"
