services:
  auth_service:
    url: "http://localhost:9001"
    routes:
      - path: "/auth/login"
        target: "/login"
      - path: "/auth/register"
        target: "/register"
  review_service:
    url: "http://localhost:9002"
    routes:
      - path: "/review/hi"
        target: "/test"
